- name: create ec2 and r53 records
  hosts: all  
  connection: local
  vars:
    sg_id: sg-0a4e2040f42d9d840
    ami_id: ami-0220d79f3f480ecf5
    environment: dev 
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }}-{{ environment }}"
      tags: # This is meta data it will be useful for filtering the data
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ environment }}"
        Name: "{{ item }}-{{ environment }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"